name: ingeritypay
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  pinput: ^5.0.0
  smart_auth: ^2.0.0
  lottie: ^3.1.3
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  flutter_secure_storage: ^9.2.2
  convex_bottom_bar: ^3.2.0
  animated_bottom_navigation_bar: ^1.3.3
  intl: ^0.19.0
  jwt_decode: ^0.3.1
  connectivity_plus: ^6.1.0
  go_router: ^14.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
   - assets/images/logo/
   - assets/images/login/
   - assets/images/signup/
   - assets/images/onboarding/
   - assets/images/icons/
   - assets/images/home/
   - assets/.env
   - assets/lotties/